# Generated by Django 3.2.12 on 2023-08-08 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopping', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shopping',
            name='height_field',
        ),
        migrations.RemoveField(
            model_name='shopping',
            name='image',
        ),
        migrations.RemoveField(
            model_name='shopping',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='shopping',
            name='width_field',
        ),
        migrations.AddField(
            model_name='userinformation',
            name='email',
            field=models.EmailField(default=None, max_length=254, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='userinformation',
            name='address',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='userinformation',
            name='date_of_birth',
            field=models.DateField(blank=True),
        ),
        migrations.AlterField(
            model_name='userinformation',
            name='phone_number',
            field=models.CharField(max_length=10, unique=True),
        ),
    ]
