# Generated by Django 3.2.12 on 2023-08-09 10:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shopping', '0002_auto_20230808_1504'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Shopping',
            new_name='ShoppingItem',
        ),
    ]
