# Generated by Django 3.2.12 on 2023-08-21 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopping', '0003_rename_shopping_shoppingitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='shoppingitem',
            name='image',
            field=models.ImageField(default='default.jpg', upload_to='item_images/'),
        ),
        migrations.DeleteModel(
            name='UserInformation',
        ),
    ]
