# Generated by Django 3.2.12 on 2023-08-22 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopping', '0005_alter_shoppingitem_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shoppingitem',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
